package com.priya.sortsmartse.model

import androidx.compose.ui.graphics.Color
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.priya.sortsmartse.ui.theme.*

@Entity(tableName = "waste_items")
data class WasteItem(
    @PrimaryKey
    val id: String,
    val name: String,
    val category: WasteCategory,
    val action: RecycleAction,
    val instruction: String,
    val howToDispose: String,
    val preparation: String,
    val why: String,
    val keywords: String = "",
    var isFavorite: Boolean = false
)

enum class WasteCategory(val title: String) {
    PLASTIC("Plastförpackningar"),
    PAPER("Pappersförpackningar"),
    GLASS("Glasförpackningar"),
    FOOD("Matavfall"),
    METAL("Metallförpackningar"),
    RESIDUAL("Restavfall"),
    HAZARDOUS("Farligt avfall")
}

enum class RecycleAction(val label: String, val bgColor: Color, val textColor: Color) {
    RECYCLE("Återvinning", InfoBlue, InfoBlueText),
    COMPOST("Matavfall", GreenSecondary, GreenPrimary),
    TRASH("Restavfall", Color(0xFFE5E7EB), Color(0xFF374151)),
    HAZARDOUS("Farligt avfall", DangerRed, DangerRedText)
}

// VA SYD Swedish Sorting Rules Mock Data
val mockWasteItems = listOf(
    WasteItem(
        id = "1",
        name = "Plastic Packaging (Plastförpackningar)",
        category = WasteCategory.PLASTIC,
        action = RecycleAction.RECYCLE,
        instruction = "Empty and place in the plastic packaging bin.",
        howToDispose = "Sort clean and empty plastic bags, bottles, and containers in the bin for 'Plastförpackningar'.",
        preparation = "Empty out food or liquids. No need to wash perfectly, just scrape them out. Separate different materials if possible (e.g., remove the lid).",
        why = "Recycled plastic becomes new packaging, garbage bags, or noise barriers. Every kilo of recycled plastic saves 2 liters of oil.",
        keywords = "plastic, bag, bottle, container, wrap, cup, plastic bottle, plastic bag, yogurt cup, shampoo bottle",
        isFavorite = true
    ),
    WasteItem(
        id = "2",
        name = "Paper Packaging (Pappersförpackningar)",
        category = WasteCategory.PAPER,
        action = RecycleAction.RECYCLE,
        instruction = "Flatten and place in paper packaging bin.",
        howToDispose = "Sort cardboard boxes, milk cartons, and paper bags in 'Pappersförpackningar'.",
        preparation = "Flatten boxes to save space in the bin. If a carton has a plastic cap, unscrew it and sort it as plastic.",
        why = "Paper fibers can be recycled up to seven times into new cartons and boxes.",
        keywords = "paper, cardboard, box, milk box, milk carton, juice, magazine, newspaper, bag, cardboard box"
    ),
    WasteItem(
        id = "3",
        name = "Food Waste (Matavfall)",
        category = WasteCategory.FOOD,
        action = RecycleAction.COMPOST,
        instruction = "Use the special brown paper bag provided by VA SYD.",
        howToDispose = "Place food scraps in the brown paper bag. When full, roll the top tightly and throw it in the brown bin (Matavfall).",
        preparation = "Let wet food drain before putting it in the bag. Do NOT use plastic bags, not even 'compostable' ones.",
        why = "VA SYD turns food waste into biogas for city buses and biofertilizer for local farming.",
        keywords = "food, apple, banana, peel, meat, bone, coffee, tea, egg, banana peel, apple core, coffee grounds, tea bag, eggshells"
    ),
    WasteItem(
        id = "4",
        name = "Colored Glass (Färgat glas)",
        category = WasteCategory.GLASS,
        action = RecycleAction.RECYCLE,
        instruction = "Place in the colored glass bin.",
        howToDispose = "Sort colored glass bottles and jars in the 'Färgat glas' bin.",
        preparation = "Empty the container and remove the lid (sort the lid as metal or plastic).",
        why = "Glass can be recycled endlessly. Mixing colored and clear glass ruins the recycling process.",
        keywords = "glass, colored, bottle, wine, beer, jar, glass bottle, glass jar"
    ),
    WasteItem(
        id = "5",
        name = "Clear Glass (Ofärgat glas)",
        category = WasteCategory.GLASS,
        action = RecycleAction.RECYCLE,
        instruction = "Place in the clear glass bin.",
        howToDispose = "Sort clear glass bottles and jars in the 'Ofärgat glas' bin.",
        preparation = "Empty the container and remove the lid.",
        why = "Do NOT throw drinking glasses or crystal here, as they contain other minerals and go to residual waste or the recycling center.",
        keywords = "glass, clear, bottle, jar, glass bottle, glass jar"
    ),
    WasteItem(
        id = "6",
        name = "Metal Packaging (Metallförpackningar)",
        category = WasteCategory.METAL,
        action = RecycleAction.RECYCLE,
        instruction = "Place in the metal packaging bin.",
        howToDispose = "Sort tin cans, aluminum foil, and metal tubes in 'Metallförpackningar'.",
        preparation = "Empty and bend sharp edges inward. Leave the plastic cap on tubes to prevent leaking.",
        why = "Metal can be recycled endlessly. Recycling aluminum saves 95% of the energy compared to making new aluminum.",
        keywords = "metal, can, aluminum, foil, tin, tube, lid, food can, soda can, aluminum foil"
    ),
    WasteItem(
        id = "7",
        name = "Residual Waste (Restavfall)",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Throw in the regular trash bin.",
        howToDispose = "Items that cannot be recycled (e.g., diapers, envelopes, vacuum bags, dish brushes) go in the 'Restavfall' bin.",
        preparation = "Put it in a regular plastic garbage bag and tie a double knot.",
        why = "Residual waste is incinerated at the Sysav plant to produce district heating and electricity for the region.",
        keywords = "trash, diaper, envelope, vacuum, brush, pen, tape, receipt, wet wipes, toothbrush, sponge"
    ),
    WasteItem(
        id = "8",
        name = "Batteries (Batterier)",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to a battery collection box or recycling center.",
        howToDispose = "Never throw batteries in the trash! Put them in the special red battery boxes or take them to an Återvinningscentral (recycling center).",
        preparation = "Tape the poles of lithium batteries to prevent fire hazards.",
        why = "Batteries contain toxic heavy metals that severely harm the environment if incinerated or landfilled.",
        keywords = "battery, batteries, electronics, toxic"
    ),
    WasteItem(
        id = "9",
        name = "Watches & Small Electronics",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to an electronics recycling bin or recycling center.",
        howToDispose = "Sort watches, phones, cables, and small toys with batteries as Electronic Waste (El-avfall).",
        preparation = "If the battery is easily removable, take it out and sort it separately as a battery.",
        why = "Electronics contain valuable metals like gold and copper that can be reused, as well as hazardous materials that need safe handling.",
        keywords = "watch, watches, phone, laptop, cable, wire, electronics, toy, mobile phone, charger"
    ),
    WasteItem(
        id = "10",
        name = "Ornaments & Ceramics",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Small items go in Residual Waste; large amounts to the Recycling Center.",
        howToDispose = "A broken ceramic mug or small ornament can go in your regular 'Restavfall' bin. Large amounts must go to the Återvinningscentral.",
        preparation = "Wrap sharp pieces in a bit of newspaper so the garbage collectors don't get cut.",
        why = "Ceramics and porcelain cannot be melted down with glass. If they end up in glass recycling, they ruin the entire batch.",
        keywords = "ornament, ornaments, ceramic, plate, mug, vase, porcelain, pottery, glass"
    ),
    WasteItem(
        id = "11",
        name = "Newspapers & Magazines",
        category = WasteCategory.PAPER,
        action = RecycleAction.RECYCLE,
        instruction = "Place in the Newspapers (Tidningar) bin.",
        howToDispose = "Sort daily newspapers, magazines, catalogs, and drawing paper here.",
        preparation = "Remove any plastic wrapping around the magazine and sort the plastic separately.",
        why = "Recycled paper fibers are spun into new newsprint or toilet paper.",
        keywords = "newspaper, magazine, catalog, paper, print, news"
    ),
    WasteItem(
        id = "12",
        name = "Plastic Wrap & Bags",
        category = WasteCategory.PLASTIC,
        action = RecycleAction.RECYCLE,
        instruction = "Place in the Plastic Packaging bin.",
        howToDispose = "Soft plastics like plastic wrap, carrier bags, and bubble wrap go in 'Plastförpackningar'.",
        preparation = "Shake off any food crumbs. Scrunch the soft plastic together to save space in the bin.",
        why = "Soft plastics are easily melted down to create new plastic bags and cables.",
        keywords = "rap, wrap, plastic wrap, foil, plastic bag, carrier bag, bubble wrap, soft plastic"
    ),
    WasteItem(
        id = "13",
        name = "Lightbulbs",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to a special Lightbulb collection box.",
        howToDispose = "LEDs, fluorescent tubes, and traditional lightbulbs must be left at an electronics collection point or recycling center.",
        preparation = "Handle with care so they don't break, as some contain toxic mercury vapor.",
        why = "Proper disposal ensures that the glass, metal, and toxic gases are handled safely and recycled.",
        keywords = "lightbulb, led, lamp, bulb, fluorescent, light"
    ),
    WasteItem(
        id = "14",
        name = "Clothing & Textiles",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.RECYCLE,
        instruction = "Donate or take to a textile recycling bin.",
        howToDispose = "Do not throw clothes in the regular trash. Take them to a secondhand store, or if broken, a textile recycling bin at the Återvinningscentral.",
        preparation = "Wash them first. Put them in a sealed plastic bag so they don't get wet or moldy in the collection bin.",
        why = "Producing textiles requires massive amounts of water and chemicals. Reusing them saves enormous resources.",
        keywords = "clothes, clothing, shirt, pants, shoes, fabric, textile, towel, sheet, old clothes"
    ),
    WasteItem(
        id = "15",
        name = "Medicines & Pills",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Return to any pharmacy (Apotek).",
        howToDispose = "Never flush medicines down the toilet or throw them in the trash. Take all leftover pills and liquids back to the pharmacy.",
        preparation = "Remove any paper packaging around the medicine and recycle it as paper. Keep the pills in their blister packs.",
        why = "Flushed medicines end up in the water supply and severely harm fish and aquatic ecosystems.",
        keywords = "medicine, pill, pills, drug, pharmacy, syrup, tablet"
    ),
    WasteItem(
        id = "16",
        name = "Paint & Chemicals",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to the Recycling Center (Farligt avfall).",
        howToDispose = "Leftover paint, nail polish, glue, bleach, and strong cleaning chemicals must go to the hazardous waste station.",
        preparation = "Keep them in their original containers so the staff knows what the chemicals are.",
        why = "Chemicals are highly toxic and can cause fires, explosions, or severe environmental damage if mixed with regular trash.",
        keywords = "paint, chemical, bleach, glue, nail polish, solvent, spray"
    ),
    WasteItem(
        id = "17",
        name = "Styrofoam",
        category = WasteCategory.PLASTIC,
        action = RecycleAction.RECYCLE,
        instruction = "Place in the Plastic Packaging bin.",
        howToDispose = "Styrofoam (Frigolit) used for packaging electronics or food should be sorted as plastic packaging.",
        preparation = "Break large pieces of styrofoam into smaller chunks so they fit in the bin.",
        why = "Styrofoam is a type of plastic and can be melted down and reused just like plastic bags.",
        keywords = "styrofoam, foam, packaging peanuts, cooler"
    ),
    WasteItem(
        id = "18",
        name = "Pizza Boxes",
        category = WasteCategory.PAPER,
        action = RecycleAction.RECYCLE,
        instruction = "Place in the Paper Packaging bin.",
        howToDispose = "Cardboard pizza boxes go into paper packaging, even if they have a few grease stains.",
        preparation = "Remove all pizza crusts and food scraps (put those in Food Waste). Flatten the box completely.",
        why = "The cardboard can still be recycled despite grease, saving fresh wood pulp.",
        keywords = "pizza, pizza box, grease, cardboard"
    ),
    WasteItem(
        id = "19",
        name = "CDs & DVDs",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Throw in the regular trash bin.",
        howToDispose = "Old CDs, DVDs, and VHS tapes cannot be recycled through standard bins. They go in Residual Waste (Restavfall).",
        preparation = "If you have a massive amount, it's better to take them to the recycling center as combustible waste.",
        why = "They are made of a complex mix of plastics and metals that standard packaging facilities cannot separate.",
        keywords = "cd, dvd, disc, vhs, tape, record, bluray"
    ),
    WasteItem(
        id = "20",
        name = "Cooking Oil",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.RECYCLE,
        instruction = "Pour into a bottle and take to a recycling center.",
        howToDispose = "Never pour cooking oil down the sink! Let it cool, pour it into a plastic bottle using a funnel, and take it to the recycling center.",
        preparation = "For small amounts (like a greasy pan), just wipe it out with paper towel and throw the paper in Food Waste.",
        why = "Oil poured down the drain solidifies and creates massive, expensive clogs in the city's sewer system.",
        keywords = "oil, cooking oil, grease, fat, frying, butter"
    ),
    WasteItem(
        id = "21",
        name = "Books",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Donate, or throw in the regular trash bin.",
        howToDispose = "Books with hard covers or glued spines cannot go in paper recycling. Throw them in Restavfall, or better yet, donate them.",
        preparation = "If you want to recycle a softcover book, you must rip out the pages to put in Paper, and throw the glued spine in the trash.",
        why = "The strong glue used in book binding ruins the paper recycling process.",
        keywords = "book, books, hardcover, paperback, novel"
    ),
    WasteItem(
        id = "22",
        name = "Furniture & Wood",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Take to the Recycling Center (Återvinningscentral).",
        howToDispose = "Chairs, tables, and planks of wood are too large for household bins. Drive them to the recycling center.",
        preparation = "Separate wood from metal (like removing metal legs from a wooden table) if possible.",
        why = "Wood is chipped and burned for local district heating, while the metal is recycled.",
        keywords = "furniture, wood, chair, table, desk, plank, timber"
    ),
    WasteItem(
        id = "23",
        name = "Coffee Cups (Takeaway)",
        category = WasteCategory.PAPER,
        action = RecycleAction.RECYCLE,
        instruction = "Place the cup in Paper, and the lid in Plastic.",
        howToDispose = "Paper takeaway cups belong in Paper Packaging. The plastic lid belongs in Plastic Packaging.",
        preparation = "Make sure the cup is empty. You do not need to wash it.",
        why = "Even though paper cups have a thin plastic lining to hold liquid, the recycling plant can separate the paper fibers from the plastic.",
        keywords = "coffee cup, takeaway, starbucks, espresso, tea cup, paper cup, cup"
    ),
WasteItem(
        id = "24",
        name = "Plastic bottle",
        category = WasteCategory.PLASTIC,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as plastic packaging.",
        howToDispose = "Sort as plastic packaging.",
        preparation = "Empty contents before recycling.",
        why = "Recycled plastic saves energy and reduces landfill waste.",
        keywords = "plastic bottle"
    ),
    WasteItem(
        id = "25",
        name = "Plastic bag",
        category = WasteCategory.PLASTIC,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as plastic packaging.",
        howToDispose = "Sort as plastic packaging.",
        preparation = "Ensure it is clean and dry.",
        why = "Can be melted down and remade into new plastic bags.",
        keywords = "plastic bag"
    ),
    WasteItem(
        id = "26",
        name = "Yogurt cup",
        category = WasteCategory.PLASTIC,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as plastic packaging.",
        howToDispose = "Sort as plastic packaging.",
        preparation = "Scrape out any leftover yogurt. No need to wash perfectly.",
        why = "Recycling reduces oil dependency.",
        keywords = "yogurt cup"
    ),
    WasteItem(
        id = "27",
        name = "Shampoo bottle",
        category = WasteCategory.PLASTIC,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as plastic packaging.",
        howToDispose = "Sort as plastic packaging.",
        preparation = "Empty the bottle. Remove the pump if it contains metal.",
        why = "Plastic packaging can be recycled many times.",
        keywords = "shampoo bottle"
    ),
    WasteItem(
        id = "28",
        name = "Pizza box",
        category = WasteCategory.PAPER,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as paper packaging.",
        howToDispose = "Sort as paper packaging.",
        preparation = "Remove all food waste. Grease stains are okay.",
        why = "Cardboard is highly recyclable and saves trees.",
        keywords = "pizza box"
    ),
    WasteItem(
        id = "29",
        name = "Newspaper",
        category = WasteCategory.PAPER,
        action = RecycleAction.RECYCLE,
        instruction = "Sort in the newspapers bin.",
        howToDispose = "Sort in the newspapers bin.",
        preparation = "Remove any plastic wrapping.",
        why = "Recycled paper is turned into new newsprint or toilet paper.",
        keywords = "newspaper"
    ),
    WasteItem(
        id = "30",
        name = "Cardboard box",
        category = WasteCategory.PAPER,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as paper packaging.",
        howToDispose = "Sort as paper packaging.",
        preparation = "Flatten to save space in the bin.",
        why = "Cardboard fibers can be recycled up to seven times.",
        keywords = "cardboard box"
    ),
    WasteItem(
        id = "31",
        name = "Receipt",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Throw in residual waste.",
        howToDispose = "Throw in residual waste.",
        preparation = "No preparation needed.",
        why = "Receipts contain thermal chemicals like BPA that ruin paper recycling.",
        keywords = "receipt"
    ),
    WasteItem(
        id = "32",
        name = "Glass bottle",
        category = WasteCategory.GLASS,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as glass packaging.",
        howToDispose = "Sort as glass packaging.",
        preparation = "Empty contents. Separate colored from clear glass.",
        why = "Glass can be recycled endlessly without loss of quality.",
        keywords = "glass bottle"
    ),
    WasteItem(
        id = "33",
        name = "Glass jar",
        category = WasteCategory.GLASS,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as glass packaging.",
        howToDispose = "Sort as glass packaging.",
        preparation = "Empty out food. Remove the metal lid.",
        why = "Recycling glass reduces emissions from manufacturing.",
        keywords = "glass jar"
    ),
    WasteItem(
        id = "34",
        name = "Food can",
        category = WasteCategory.METAL,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as metal packaging.",
        howToDispose = "Sort as metal packaging.",
        preparation = "Empty out food and bend sharp edges inward.",
        why = "Metal can be recycled endlessly.",
        keywords = "food can"
    ),
    WasteItem(
        id = "35",
        name = "Soda can",
        category = WasteCategory.METAL,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as metal packaging or use a Pant (deposit) machine.",
        howToDispose = "Sort as metal packaging or use a Pant (deposit) machine.",
        preparation = "Do not crush if using a Pant machine.",
        why = "Recycling aluminum saves 95% of the energy needed to make new aluminum.",
        keywords = "soda can"
    ),
    WasteItem(
        id = "36",
        name = "Aluminum foil",
        category = WasteCategory.METAL,
        action = RecycleAction.RECYCLE,
        instruction = "Sort as metal packaging.",
        howToDispose = "Sort as metal packaging.",
        preparation = "Scrape off major food residue.",
        why = "Aluminum is highly valuable and easily recycled.",
        keywords = "aluminum foil"
    ),
    WasteItem(
        id = "37",
        name = "Banana peel",
        category = WasteCategory.FOOD,
        action = RecycleAction.COMPOST,
        instruction = "Sort as food waste.",
        howToDispose = "Sort as food waste.",
        preparation = "Place in the brown paper compost bag.",
        why = "Turned into biogas and biofertilizer.",
        keywords = "banana peel"
    ),
    WasteItem(
        id = "38",
        name = "Apple core",
        category = WasteCategory.FOOD,
        action = RecycleAction.COMPOST,
        instruction = "Sort as food waste.",
        howToDispose = "Sort as food waste.",
        preparation = "Place in the brown paper compost bag.",
        why = "Creates nutrient-rich compost for local farms.",
        keywords = "apple core"
    ),
    WasteItem(
        id = "39",
        name = "Coffee grounds",
        category = WasteCategory.FOOD,
        action = RecycleAction.COMPOST,
        instruction = "Sort as food waste.",
        howToDispose = "Sort as food waste.",
        preparation = "Filters can also be included in food waste.",
        why = "Excellent source of nitrogen for compost.",
        keywords = "coffee grounds"
    ),
    WasteItem(
        id = "40",
        name = "Tea bag",
        category = WasteCategory.FOOD,
        action = RecycleAction.COMPOST,
        instruction = "Sort as food waste.",
        howToDispose = "Sort as food waste.",
        preparation = "Remove the staple if there is one.",
        why = "Easily broken down in the composting process.",
        keywords = "tea bag"
    ),
    WasteItem(
        id = "41",
        name = "Eggshells",
        category = WasteCategory.FOOD,
        action = RecycleAction.COMPOST,
        instruction = "Sort as food waste.",
        howToDispose = "Sort as food waste.",
        preparation = "No preparation needed.",
        why = "Adds valuable calcium to biofertilizer.",
        keywords = "eggshells"
    ),
    WasteItem(
        id = "42",
        name = "Diaper",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Throw in residual waste.",
        howToDispose = "Throw in residual waste.",
        preparation = "Wrap securely in a plastic bag.",
        why = "Cannot be recycled due to human waste and mixed materials.",
        keywords = "diaper"
    ),
    WasteItem(
        id = "43",
        name = "Wet wipes",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Throw in residual waste. Never flush!",
        howToDispose = "Throw in residual waste. Never flush!",
        preparation = "Put in a plastic bag.",
        why = "Flushing wet wipes causes massive sewer clogs.",
        keywords = "wet wipes"
    ),
    WasteItem(
        id = "44",
        name = "Toothbrush",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Throw in residual waste.",
        howToDispose = "Throw in residual waste.",
        preparation = "No preparation needed.",
        why = "Made of mixed plastics that standard plants cannot separate.",
        keywords = "toothbrush"
    ),
    WasteItem(
        id = "45",
        name = "Sponge",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Throw in residual waste.",
        howToDispose = "Throw in residual waste.",
        preparation = "No preparation needed.",
        why = "Synthetic sponges are non-recyclable mixed plastics.",
        keywords = "sponge"
    ),
    WasteItem(
        id = "46",
        name = "Battery",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to a battery collection point.",
        howToDispose = "Take to a battery collection point.",
        preparation = "Tape the ends of lithium batteries.",
        why = "Contains toxic heavy metals that must not leak into nature.",
        keywords = "battery"
    ),
    WasteItem(
        id = "47",
        name = "Paint",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to a recycling center.",
        howToDispose = "Take to a recycling center.",
        preparation = "Keep in its original container.",
        why = "Toxic chemicals require specialized, safe disposal.",
        keywords = "paint"
    ),
    WasteItem(
        id = "48",
        name = "Medicine",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Return to a pharmacy (Apotek).",
        howToDispose = "Return to a pharmacy (Apotek).",
        preparation = "Keep pills in blister packs, recycle the cardboard box.",
        why = "Protects aquatic life from hormonal and chemical disruption.",
        keywords = "medicine"
    ),
    WasteItem(
        id = "49",
        name = "Mobile phone",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to electronics recycling.",
        howToDispose = "Take to electronics recycling.",
        preparation = "Erase your personal data first.",
        why = "Contains gold, copper, and rare earth metals that must be recovered.",
        keywords = "mobile phone"
    ),
    WasteItem(
        id = "50",
        name = "Charger",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to electronics recycling.",
        howToDispose = "Take to electronics recycling.",
        preparation = "Tie the cable neatly.",
        why = "Copper wire is highly valuable and easily recycled.",
        keywords = "charger"
    ),
    WasteItem(
        id = "51",
        name = "Old clothes",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.RECYCLE,
        instruction = "Donate or put in textile recycling.",
        howToDispose = "Donate or put in textile recycling.",
        preparation = "Wash them and seal in a plastic bag.",
        why = "Textile production uses massive resources; reuse is critical.",
        keywords = "old clothes"
    ),
    WasteItem(
        id = "52",
        name = "Light bulb",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.HAZARDOUS,
        instruction = "Take to electronics recycling.",
        howToDispose = "Take to electronics recycling.",
        preparation = "Handle with care.",
        why = "May contain hazardous gases like mercury.",
        keywords = "light bulb"
    ),
    WasteItem(
        id = "53",
        name = "Cooking oil",
        category = WasteCategory.HAZARDOUS,
        action = RecycleAction.RECYCLE,
        instruction = "Bottle it and take to recycling center.",
        howToDispose = "Bottle it and take to recycling center.",
        preparation = "Let it cool and pour into a plastic bottle.",
        why = "Prevents severe clogs in the sewer system and can be turned into biodiesel.",
        keywords = "cooking oil"
    ),
WasteItem(
        id = "54",
        name = "Diapers",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "diapers, trash, residual, restavfall"
    ),
    WasteItem(
        id = "55",
        name = "Wet wipes",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall, do not flush",
        howToDispose = "Put in restavfall, do not flush",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "wet wipes, trash, residual, restavfall"
    ),
    WasteItem(
        id = "56",
        name = "Used tissues",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "used tissues, trash, residual, restavfall"
    ),
    WasteItem(
        id = "57",
        name = "Cotton pads",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "cotton pads, trash, residual, restavfall"
    ),
    WasteItem(
        id = "58",
        name = "Cotton buds",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "cotton buds, trash, residual, restavfall"
    ),
    WasteItem(
        id = "59",
        name = "Vacuum cleaner dust",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "vacuum cleaner dust, trash, residual, restavfall"
    ),
    WasteItem(
        id = "60",
        name = "Dirty paper towels",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "dirty paper towels, trash, residual, restavfall"
    ),
    WasteItem(
        id = "61",
        name = "Greasy baking paper",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "greasy baking paper, trash, residual, restavfall"
    ),
    WasteItem(
        id = "62",
        name = "Toothbrush",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "toothbrush, trash, residual, restavfall"
    ),
    WasteItem(
        id = "63",
        name = "Dish sponge",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "dish sponge, trash, residual, restavfall"
    ),
    WasteItem(
        id = "64",
        name = "Cleaning cloth",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "cleaning cloth, trash, residual, restavfall"
    ),
    WasteItem(
        id = "65",
        name = "Broken ceramic plate",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Wrap safely and put in restavfall",
        howToDispose = "Wrap safely and put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "broken ceramic plate, trash, residual, restavfall"
    ),
    WasteItem(
        id = "66",
        name = "Broken porcelain cup",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Wrap safely and put in restavfall",
        howToDispose = "Wrap safely and put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "broken porcelain cup, trash, residual, restavfall"
    ),
    WasteItem(
        id = "67",
        name = "Drinking glass",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Wrap safely and put in restavfall",
        howToDispose = "Wrap safely and put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "drinking glass, trash, residual, restavfall"
    ),
    WasteItem(
        id = "68",
        name = "Mirror pieces",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Wrap safely and put in restavfall, or take large pieces to recycling center",
        howToDispose = "Wrap safely and put in restavfall, or take large pieces to recycling center",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "mirror pieces, trash, residual, restavfall"
    ),
    WasteItem(
        id = "69",
        name = "Cat litter",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "cat litter, trash, residual, restavfall"
    ),
    WasteItem(
        id = "70",
        name = "Dog poop bag",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "dog poop bag, trash, residual, restavfall"
    ),
    WasteItem(
        id = "71",
        name = "Cigarette butts",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "cigarette butts, trash, residual, restavfall"
    ),
    WasteItem(
        id = "72",
        name = "Chewing gum",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "chewing gum, trash, residual, restavfall"
    ),
    WasteItem(
        id = "73",
        name = "Dust and hair",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "dust and hair, trash, residual, restavfall"
    ),
    WasteItem(
        id = "74",
        name = "Small rubber items",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "small rubber items, trash, residual, restavfall"
    ),
    WasteItem(
        id = "75",
        name = "Old dish brush",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "old dish brush, trash, residual, restavfall"
    ),
    WasteItem(
        id = "76",
        name = "Toothpaste tube",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall if not accepted as plastic packaging",
        howToDispose = "Put in restavfall if not accepted as plastic packaging",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "toothpaste tube, trash, residual, restavfall"
    ),
    WasteItem(
        id = "77",
        name = "Dirty plastic wrap",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "dirty plastic wrap, trash, residual, restavfall"
    ),
    WasteItem(
        id = "78",
        name = "Dirty aluminum foil",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "dirty aluminum foil, trash, residual, restavfall"
    ),
    WasteItem(
        id = "79",
        name = "Dirty pizza box parts",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put greasy parts in restavfall",
        howToDispose = "Put greasy parts in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "dirty pizza box parts, trash, residual, restavfall"
    ),
    WasteItem(
        id = "80",
        name = "Receipts",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "receipts, trash, residual, restavfall"
    ),
    WasteItem(
        id = "81",
        name = "Stickers and labels",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "stickers and labels, trash, residual, restavfall"
    ),
    WasteItem(
        id = "82",
        name = "Gift wrapping with glitter/plastic",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "gift wrapping with glitter/plastic, trash, residual, restavfall"
    ),
    WasteItem(
        id = "83",
        name = "Ribbon and tape",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "ribbon and tape, trash, residual, restavfall"
    ),
    WasteItem(
        id = "84",
        name = "Candle wax leftovers",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "candle wax leftovers, trash, residual, restavfall"
    ),
    WasteItem(
        id = "85",
        name = "Used makeup wipes",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "used makeup wipes, trash, residual, restavfall"
    ),
    WasteItem(
        id = "86",
        name = "Empty makeup packaging mixed material",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall if not recyclable",
        howToDispose = "Put in restavfall if not recyclable",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "empty makeup packaging mixed material, trash, residual, restavfall"
    ),
    WasteItem(
        id = "87",
        name = "Razor blade cartridge",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Wrap safely and put in restavfall",
        howToDispose = "Wrap safely and put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "razor blade cartridge, trash, residual, restavfall"
    ),
    WasteItem(
        id = "88",
        name = "Broken pen",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "broken pen, trash, residual, restavfall"
    ),
    WasteItem(
        id = "89",
        name = "Pencil shavings",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "pencil shavings, trash, residual, restavfall"
    ),
    WasteItem(
        id = "90",
        name = "Small broken toys without battery",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "small broken toys without battery, trash, residual, restavfall"
    ),
    WasteItem(
        id = "91",
        name = "Balloons",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "balloons, trash, residual, restavfall"
    ),
    WasteItem(
        id = "92",
        name = "Disposable gloves",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "disposable gloves, trash, residual, restavfall"
    ),
    WasteItem(
        id = "93",
        name = "Face mask",
        category = WasteCategory.RESIDUAL,
        action = RecycleAction.TRASH,
        instruction = "Put in restavfall",
        howToDispose = "Put in restavfall",
        preparation = "No special preparation needed unless specified.",
        why = "Items that cannot be recycled are incinerated to produce energy.",
        keywords = "face mask, trash, residual, restavfall"
    )
)
